package ind.shubhamn.precisrest.service;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

import ind.shubhamn.precisrest.dao.UrlShortenerDAO;
import ind.shubhamn.precisrest.exception.ShortUrlAlreadyExistsException;
import ind.shubhamn.precisrest.model.ShortenedUrl;
import java.util.Optional;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

public class UrlShortenerServiceCustomAliasTest {

    @InjectMocks private UrlShortenerService urlShortenerService;

    @Mock private UrlShortenerDAO urlShortenerDAO;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    public void testShortenUrlWithCustomAlias_Success() throws Exception {
        // Arrange
        String longUrl = "https://www.example.com";
        String customAlias = "my-custom-link";

        when(urlShortenerDAO.findByShortUrl(customAlias)).thenReturn(Optional.empty());
        when(urlShortenerDAO.save(any(ShortenedUrl.class)))
                .thenAnswer(invocation -> invocation.getArgument(0));

        // Act
        ShortenedUrl result = urlShortenerService.shortenUrl(longUrl, customAlias);

        // Assert
        assertNotNull(result);
        assertEquals(customAlias, result.getShortUrl());
        assertEquals(longUrl, result.getLongUrl());
        verify(urlShortenerDAO, times(1)).findByShortUrl(customAlias);
        verify(urlShortenerDAO, times(1)).save(any(ShortenedUrl.class));
    }

    @Test
    public void testShortenUrlWithCustomAlias_AlreadyExists() {
        // Arrange
        String longUrl = "https://www.example.com";
        String customAlias = "existing-alias";

        ShortenedUrl existingUrl = new ShortenedUrl();
        existingUrl.setShortUrl(customAlias);
        existingUrl.setLongUrl("https://www.other.com");

        when(urlShortenerDAO.findByShortUrl(customAlias)).thenReturn(Optional.of(existingUrl));

        // Act & Assert
        ShortUrlAlreadyExistsException exception =
                assertThrows(
                        ShortUrlAlreadyExistsException.class,
                        () -> urlShortenerService.shortenUrl(longUrl, customAlias));

        assertTrue(exception.getMessage().contains(customAlias));
        assertTrue(exception.getMessage().contains("already in use"));
        verify(urlShortenerDAO, times(1)).findByShortUrl(customAlias);
        verify(urlShortenerDAO, never()).save(any(ShortenedUrl.class));
    }

    @Test
    public void testShortenUrlWithCustomAlias_DifferentUrls() throws Exception {
        // Arrange
        String longUrl1 = "https://www.example1.com";
        String longUrl2 = "https://www.example2.com";
        String customAlias1 = "link1";
        String customAlias2 = "link2";

        when(urlShortenerDAO.findByShortUrl(anyString())).thenReturn(Optional.empty());
        when(urlShortenerDAO.save(any(ShortenedUrl.class)))
                .thenAnswer(invocation -> invocation.getArgument(0));

        // Act
        ShortenedUrl result1 = urlShortenerService.shortenUrl(longUrl1, customAlias1);
        ShortenedUrl result2 = urlShortenerService.shortenUrl(longUrl2, customAlias2);

        // Assert
        assertNotNull(result1);
        assertNotNull(result2);
        assertEquals(customAlias1, result1.getShortUrl());
        assertEquals(customAlias2, result2.getShortUrl());
        assertEquals(longUrl1, result1.getLongUrl());
        assertEquals(longUrl2, result2.getLongUrl());
        assertNotEquals(result1.getShortUrl(), result2.getShortUrl());
        verify(urlShortenerDAO, times(2)).save(any(ShortenedUrl.class));
    }

    @Test
    public void testShortenUrl_AutoGenerated_StillWorks() throws Exception {
        // Arrange
        String longUrl = "https://www.google.com";

        when(urlShortenerDAO.save(any(ShortenedUrl.class)))
                .thenAnswer(invocation -> invocation.getArgument(0));

        // Act
        ShortenedUrl result = urlShortenerService.shortenUrl(longUrl, null);

        // Assert
        assertNotNull(result);
        assertNotNull(result.getShortUrl());
        assertEquals(8, result.getShortUrl().length()); // Auto-generated URLs are 8 characters
        assertEquals(longUrl, result.getLongUrl());
        verify(urlShortenerDAO, times(1)).save(any(ShortenedUrl.class));
    }
}
